# Initial service
apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: logstash
  labels:
    # Important, associate here the service to the pod app name !
    name: logstash
spec:
  ports:
    - port: 5044